language: ruby
cache: bundler
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2

secure: "A+gFpnI5cZTDkL7gJZ8uZjVrKmKGUMZF4mLthEX8vHpvy0IB+v82obscbxYs3HczF7eSshbfvpdJ6L2fWtVNV5lV5wqVeQZNp751+0yHrfY2CPF0cL9qf1ysF6Pfh6omFl9b1KTxI+08tK/b0n41m6PfQUCYf7AfAzAZdBZs2/UDPYvP5MzdKTMJPl9WWNcb/cqP9wgCqXBpX1IXmpmIQjklvLZjJhxFeFT1xYwjL1CN/yxblDBowZ1s85xfaay4KbXaaEAkYezQmTYu6tZhhDEtpfJqDqsDRkklgC9/I/usvebr/uZJK6iKaD9RMrjtYrXy1el+qlGwBNWPtAqkH0ncaTtwVSyujzkKMwknBlw/+Tr/S2vQH0KJOKEiw4Fkqr6Jzm/bukP6r5+6eOCIxiU66HWzxkKJY0yWKWqcfHM+tHFUqYorsqX/RKgGQR/pKTyxi7GldSH0X9I1WV4G4yfzsaaxHPmv3bZtIev3fspIUc8IcKvg859J318ELEvcOvm4aAg3z2KsX5b1LmHL9X6zEFOmy2F1p6UsSXW4aoL0LU1U6KX6lWwm3TMtTvE6ggXdwzruiVrwcJ8GcJ0eruUyEQX1Lzll4zHMMkjAWTk8eqXeCGlZBlCCi9M5DWMuAOC2SzaofU9SO10aLG+TzBCuGhKdMkbqJ8dDV/fweNg="
